src/main/java/br/apolo/biodunet/data/model/Enzyme.java
package br.apolo.biodunet.data.model;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import br.apolo.data.model.AuditableBaseEntity;

@Entity
@Table(name = "enzyme")
public class Enzyme extends AuditableBaseEntity {
	
	private static final long serialVersionUID = 5751401566413965861L;

	@Column(unique = true, nullable = false)
	private String name;
	
	@Column(unique = true, nullable = false)
	private String accession;
	
	@Column
	private String principalValue;
	
	@Column
	private Long principalCourtPosition;
	
	@Column
	private String complementValue;
	
	@Column
	private Long complementCourtPosition;
	
	@Transient
	private List<String> plasmidCourtPosition;
	
	@Transient
	private List<Long> sequenceCourtPosition;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPrincipalValue() {
		return principalValue;
	}

	public void setPrincipalValue(String principalValue) {
		this.principalValue = principalValue;
	}

	public Long getPrincipalCourtPosition() {
		return principalCourtPosition;
	}

	public void setPrincipalCourtPosition(Long principalCourtPosition) {
		this.principalCourtPosition = principalCourtPosition;
	}

	public String getComplementValue() {
		return complementValue;
	}

	public void setComplementValue(String complementValue) {
		this.complementValue = complementValue;
	}

	public Long getComplementCourtPosition() {
		return complementCourtPosition;
	}

	public void setComplementCourtPosition(Long complementCourtPosition) {
		this.complementCourtPosition = complementCourtPosition;
	}

	public String getAccession() {
		return accession;
	}

	public void setAccession(String accession) {
		this.accession = accession;
	}

	public List<String> getPlasmidCourtPosition() {
		return plasmidCourtPosition;
	}

	public void setPlasmidCourtPosition(List<String> plasmidCourtPosition) {
		this.plasmidCourtPosition = plasmidCourtPosition;
	}

	public List<Long> getSequenceCourtPosition() {
		return sequenceCourtPosition;
	}

	public void setSequenceCourtPosition(List<Long> sequenceCourtPosition) {
		this.sequenceCourtPosition = sequenceCourtPosition;
	}
	
	public Long getFirstSequenceCourtPosition() {
		Long result = 0L;
		
		if (this.sequenceCourtPosition != null && !this.sequenceCourtPosition.isEmpty()) {
			result = this.sequenceCourtPosition.get(0);
		}
		
		return result;
	}
	
	public Long getLastSequenceCourtPosition() {
		Long result = 0L;
		
		if (this.sequenceCourtPosition != null && !this.sequenceCourtPosition.isEmpty()) {
			result = this.sequenceCourtPosition.get(this.sequenceCourtPosition.size() - 1);
		}
		
		return result;
	}

}

src/main/metamodels/br/apolo/biodunet/data/model/Enzyme_.java
package br.apolo.biodunet.data.model;

import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(Enzyme.class)
public abstract class Enzyme_ extends br.apolo.data.model.BaseEntity_ {

	public static volatile SingularAttribute<Enzyme, String> name;
	public static volatile SingularAttribute<Enzyme, String> accession;

}

src/main/java/br/apolo/biodunet/web/controller/EnzymeController.java
package br.apolo.biodunet.web.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;

import br.apolo.biodunet.business.service.EnzymeService;
import br.apolo.biodunet.business.service.PlasmidService;
import br.apolo.biodunet.data.helper.FileNCBIHelper;
import br.apolo.biodunet.data.model.Enzyme;
import br.apolo.biodunet.web.model.EnzymesFormModel;
import br.apolo.biodunet.web.model.FileFormModel;
import br.apolo.business.model.SearchResult;
import br.apolo.common.util.MessageBundle;
import br.apolo.security.SecuredEnum;
import br.apolo.security.UserPermission;
import br.apolo.web.controller.BaseController;
import br.apolo.web.enums.Navigation;

@Controller
@RequestMapping(value = "/enzyme")
public class EnzymeController extends BaseController<Enzyme> {

	@Autowired
	PlasmidService plasmidService;
	
	@Autowired
	EnzymeService enzymeService;

	@RequestMapping(value = "list", method = RequestMethod.GET)
	public ModelAndView list() {
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_LIST.getPath());

		List<Enzyme> enzymeList = enzymeService.list();

		mav.addObject("enzymeList", enzymeList);

		return mav;
	}

	@SecuredEnum(UserPermission.DATA_MANAGER)
	@RequestMapping(value = "save", method = RequestMethod.POST)
	public ModelAndView save(Enzyme entity) {
		ModelAndView mav = new ModelAndView();

		if (entity != null) {
			enzymeService.save(entity);

			mav = list();

			mav.addObject("msg", true);
			mav.addObject("message",
					MessageBundle.getMessageBundle("common.msg.save.success"));
		}

		return mav;
	}
	
	@SecuredEnum(UserPermission.DATA_MANAGER)
	@RequestMapping(value = "save-batch", method = RequestMethod.POST)
	public ModelAndView saveBatch(@ModelAttribute("enzymes") EnzymesFormModel enzymes, Model map) {
		ModelAndView mav = new ModelAndView();

		boolean hasErrors = false;
		Integer successCount = 0;
		Integer errorCount = 0;
		
		if (enzymes != null && enzymes.getEnzymes() != null && !enzymes.getEnzymes().isEmpty()) {
			for (Enzyme enzyme : enzymes.getEnzymes()) {
				if (enzyme != null && enzyme.getAccession() != null && enzyme.getName() != null) {
					try {
						enzymeService.save(enzyme);
						successCount++;
					} catch (Exception e) {
						errorCount++;
						hasErrors = true;
					}
				}
			}
			
			mav = list();

			if (hasErrors) {
				if (successCount == 0) {
					mav.addObject("error", true);	
				} else {
					mav.addObject("warn", true);
				}
				
				mav.addObject("message", MessageBundle.getMessageBundle("common.msg.save.results", successCount, errorCount));
			} else {
				mav.addObject("msg", true);
				mav.addObject("message", MessageBundle.getMessageBundle("common.msg.save.all.success", successCount));
			}
		}

		return mav;
	}

	@SecuredEnum(UserPermission.DATA_MANAGER)
	@RequestMapping(value = "new-batch", method = RequestMethod.GET)
	public ModelAndView createBatch() {
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_NEW_BATCH.getPath());
		return mav;
	}

	@SecuredEnum(UserPermission.DATA_MANAGER)
	@RequestMapping(value = "new-batch-proccess-file", method = RequestMethod.POST)
	public ModelAndView createBatchProccessFile(
			@ModelAttribute("uploadForm") FileFormModel uploadForm,
					Model map) {
		
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_NEW_BATCH_APPROVE_LIST.getPath());
		
		List<MultipartFile> files = uploadForm.getFiles();

		List<String> fileNames = new ArrayList<String>();
		
		List<Enzyme> enzymes = new ArrayList<Enzyme>();
		
		if(null != files && files.size() > 0) {
			for (MultipartFile multipartFile : files) {

				String fileName = multipartFile.getOriginalFilename();
				fileNames.add(fileName);
				
	    		if(multipartFile != null) {
	    			FileNCBIHelper helper = new FileNCBIHelper();
	    			
	        		try {
						enzymes = helper.enzymesFileConverter(multipartFile);
						mav.addObject("enzymeList", enzymes);
					} catch (IOException e) {
						e.printStackTrace();
					}
	                
	    		}
			}
		}
		
		return mav;
	}
	
	@Override
	@SecuredEnum(UserPermission.DATA_MANAGER)
	@RequestMapping(value = "new", method = RequestMethod.GET)
	public ModelAndView create() {
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_NEW.getPath());

		mav.addObject("enzyme", new Enzyme());
		mav.addObject("readOnly", false);

		return mav;
	}

	@Override
	@SecuredEnum(UserPermission.DATA_MANAGER)
	@RequestMapping(value = "edit/{id}", method = RequestMethod.GET)
	public ModelAndView edit(@PathVariable Long id) {
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_EDIT.getPath());
		
		Enzyme enzyme = enzymeService.find(id);
		
		mav.addObject("enzyme", enzyme);
		mav.addObject("readOnly", false);
		
		return mav;
	}

	@Override
	@SecuredEnum(UserPermission.DATA_MANAGER)
	@RequestMapping(value = "remove/{id}", method = RequestMethod.GET)
	public ModelAndView remove(@PathVariable Long id) {
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_LIST.getPath());
		
		Enzyme enzyme = enzymeService.find(id);
		
		if (enzyme != null) {
			enzymeService.remove(enzyme);
			
			mav = list();
			
			mav.addObject("msg", true);
			mav.addObject("message", MessageBundle.getMessageBundle("common.msg.remove.success"));
		} else {
			mav = list();
			
			mav.addObject("error", true);
			mav.addObject("message", MessageBundle.getMessageBundle("common.msg.remove.fail"));
		}
		
		return mav;
	}
	
	@RequestMapping(value = "search-form", method = RequestMethod.GET)
	public ModelAndView searchForm() {
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_SEARCH.getPath());
		
		return mav;
	}
	
	@RequestMapping(value = "search", method = RequestMethod.POST)
	public ModelAndView search(@ModelAttribute("param") String param) {
		ModelAndView mav = new ModelAndView(Navigation.ENZYME_LIST.getPath());
		
		SearchResult<Enzyme> result = enzymeService.search(param);
		
		List<Enzyme> enzymeList = result.getResults();
		
		mav.addObject("enzymeList", enzymeList);
		
		return mav;
	}

	@InitBinder
	public void initBinder(WebDataBinder dataBinder) {
		dataBinder.setAutoGrowCollectionLimit(Integer.MAX_VALUE);
	}
}

src/main/webapp/WEB-INF/views/enzyme/_enzyme-form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<input type="hidden" id="id" name="id" value="${enzyme.id}" />

<div class="row">
	<div class="span12">
		<label for="name">
			<s:message code="common.name" />
		</label>
		<input type="text" id="name" name="name" class="input-block-level" value="${enzyme.name}" <c:if test="${readOnly}">readonly="true"</c:if> />
	</div>
</div>
<div class="row">
	<div class="span12">
		<label for="name">
			<s:message code="common.accession" />
		</label>
		<input type="text" id="accession" name="accession" class="input-block-level" value="${enzyme.accession}" <c:if test="${readOnly}">readonly="true"</c:if> />
	</div>
</div>
<div class="row">
	<div class="span6">
		<label for="name">
			<s:message code="enzyme.codon.principal.value" />
		</label>
		<input type="text" id="principalValue" name="principalValue" class="input-block-level" value="${enzyme.principalValue}" <c:if test="${readOnly}">readonly="true"</c:if> />
	</div>
	<div class="span6">
		<label for="name">
			<s:message code="enzyme.codon.principal.position" />
		</label>
		<input type="text" id="principalCourtPosition" name="principalCourtPosition" class="input-block-level" value="${enzyme.principalCourtPosition}" <c:if test="${readOnly}">readonly="true"</c:if> />
	</div>
</div>
<div class="row">
	<div class="span6">
		<label for="name">
			<s:message code="enzyme.codon.compl.value" />
		</label>
		<input type="text" id="complementValue" name="complementValue" class="input-block-level" value="${enzyme.complementValue}" <c:if test="${readOnly}">readonly="true"</c:if> />
	</div>
	<div class="span6">
		<label for="name">
			<s:message code="enzyme.codon.compl.position" />
		</label>
		<input type="text" id="complementCourtPosition" name="complementCourtPosition" class="input-block-level" value="${enzyme.complementCourtPosition}" <c:if test="${readOnly}">readonly="true"</c:if> />
	</div>
</div>

src/main/webapp/WEB-INF/views/enzyme/_search-form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<form id="form" class="form-search" action="<s:url value="/enzyme/search"></s:url>" method="post">
	<div class="input-append">
		<input type="text" id="param" name="param" class="span3 search-query" placeholder='<s:message code="enzyme.search.field" />'>
		<button type="submit" class="btn">
			<s:message code="common.search" /> 
		</button>
	</div>
</form>

src/main/webapp/WEB-INF/views/enzyme/edit.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<fieldset>
	<legend>
		<s:message code="enzyme.edit.title" />
	</legend>
	
	<form id="userForm" action="<s:url value="/enzyme/save"></s:url>" method="post">
		<jsp:include page='_enzyme-form.jsp'></jsp:include>
		
		<div class="form-actions">
			<button type="submit" class="btn btn-primary">
				<s:message code="common.save" /> 
			</button>

			<a href='<s:url value="/"></s:url>' class="btn">
				<s:message code="common.cancel" />
			</a>
		</div>
	</form>

</fieldset>

src/main/webapp/WEB-INF/views/enzyme/list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<jsp:include page='_search-form.jsp'></jsp:include>

<fieldset>
	<legend>
		<s:message code="enzyme.list.title" />
	</legend>
	
	<table class="table table-striped table-hover table-bordered">
		<thead>
			<tr>
				<th>
					#
				</th>
				<th>
					<s:message code="common.name" />
				</th>
				<th>
					<s:message code="common.accession" />
				</th>
				<th>
					<s:message code="enzyme.codon.principal.value" />
				</th>
				<th>
					<s:message code="enzyme.codon.principal.position" />
				</th>
				<th>
					<s:message code="enzyme.codon.compl.value" />
				</th>
				<th>
					<s:message code="enzyme.codon.compl.position" />
				</th>
				<th>
					<s:message code="common.actions" />
				</th>
			</tr>
		</thead>
		
		<tbody>
			<c:forEach items="${enzymeList}" var="enzyme">
				<tr>
					<td>
						${enzyme.id}
					</td>
					<td>
						${enzyme.name}
					</td>
					<td>
						${enzyme.accession}
					</td>
					<td>
						${enzyme.principalValue}
					</td>
					<td>
						${enzyme.principalCourtPosition}
					</td>
					<td>
						${enzyme.complementValue}
					</td>
					<td>
						${enzyme.complementCourtPosition}
					</td>
					<td>
						<div class="btn-group">
							<a href='<s:url value="/enzyme/edit"></s:url>/${enzyme.id}' class="btn" tabindex="-1">
								<s:message code="common.edit" />
							</a>
							<button class="btn dropdown-toggle" data-toggle="dropdown" tabindex="-1">
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li>
									<a href='<s:url value="/enzyme/remove"></s:url>/${enzyme.id}'>
										<s:message code="common.remove" />
									</a>
								</li>
							</ul>
						</div>
					</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>

</fieldset>

src/main/webapp/WEB-INF/views/enzyme/new-batch-approve-list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<script type="text/javascript" src='<c:url value="/resources/app/js/enzyme.js" />'></script>

<fieldset>
	<legend>
		<s:message code="enzyme.new.batch.title" />
	</legend>
	
	<div class="row">
		<div class="span12">
			<form class="form-inline enzymeForm" action="<s:url value="/enzyme/save-batch"></s:url>" method="post">
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">
						<s:message code="common.save.all" /> 
					</button>
		
					<a href='<s:url value="/"></s:url>' class="btn">
						<s:message code="common.cancel" />
					</a>
				</div>
			
				<table class="table table-striped table-hover table-bordered">
					<thead>
						<tr>
							<th class="span1">
								#
							</th>
							<th class="span2">
								<s:message code="common.name" />
							</th>
							<th class="span2">
								<s:message code="common.accession" />
							</th>
							<th class="span2">
								<s:message code="enzyme.codon.principal.value" />
							</th>
							<th class="span1">
								<s:message code="enzyme.codon.principal.position" />
							</th>
							<th class="span2">
								<s:message code="enzyme.codon.compl.value" />
							</th>
							<th class="span1">
								<s:message code="enzyme.codon.compl.position" />
							</th>
							<th class="span1">
							</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${enzymeList}" var="enzyme" varStatus="status">
							<tr id="enzyme_${enzyme.accession}">
								<td class="span1">
									<span>${status.count} </span>
								</td>
								<td class="span2">
									<input type="text" name="enzymes[${status.count - 1}].name" class="input-block-level" value="${enzyme.name}" />
								</td>
								<td class="span2">
									<input type="text" name="enzymes[${status.count - 1}].accession" class="input-block-level" value="${enzyme.accession}" />
								</td>
								<td class="span2">
									<input type="text" name="enzymes[${status.count - 1}].principalValue" class="input-block-level" value="${enzyme.principalValue}" />
								</td>
								<td class="span1">
									<input type="text" name="enzymes[${status.count - 1}].principalCourtPosition" class="input-block-level" value="${enzyme.principalCourtPosition}" />
								</td>
								<td class="span2">
									<input type="text" name="enzymes[${status.count - 1}].complementValue" class="input-block-level" value="${enzyme.complementValue}" />
								</td>
								<td class="span1">
									<input type="text" name="enzymes[${status.count - 1}].complementCourtPosition" class="input-block-level" value="${enzyme.complementCourtPosition}" />
								</td>
								<td class="span1">
									<button class="btn" onclick="$('#enzyme_${enzyme.accession}').remove()">
										<span class="icon-trash"></span>
									</button>
								</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</form>
		</div>
	</div>

</fieldset>

src/main/webapp/WEB-INF/views/enzyme/search.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<fieldset>
	<legend>
		<s:message code="enzyme.search.title" />
	</legend>
	
	<jsp:include page='_search-form.jsp'></jsp:include>

</fieldset>

src/main/webapp/WEB-INF/views/enzyme/select-enzymes-assay.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<fieldset>
	<legend>
		<s:message code="enzyme.elective.title" />
	</legend>

	<form id="plasmidForm" action="<s:url value="/plasmid/input-data-assay"></s:url>" method="post">
		
		<div class="row">
			<div class="span4">
				<label for="plasmidId">
					<s:message code="plasmid" />
				</label>
				<input type="hidden" id="plasmidId" name="plasmidId" value="${plasmid.id}" readonly="readonly"/>
				<input type="text" id="plasmidAccession" name="plasmidAccession" value="${plasmid.accession}" readonly="readonly"/>
			</div>
			<div class="span4">
				<label for="enzymeInitialId">
					<s:message code="enzyme.initial" />
				</label>
				<input type="text" id="enzymeInitialName" name="enzymeInitialName" readonly="readonly"/>
				<input type="text" id="enzymeInitialAccession" name="enzymeInitialAccession" readonly="readonly"/>
				<input type="hidden" id="enzymeInitialId" name="enzymeInitialId" readonly="readonly"/>
				<input type="hidden" id="enzymePlasmidInitialCourtPositionList" name="enzymePlasmidInitialCourtPositionList" readonly="readonly"/>
				
				<label for="enzymeSequenceInitialCourtPosition">
					<s:message code="enzyme.sequence.court.initial" />
				</label>
				<input type="text" id="enzymeSequenceInitialCourtPosition" name="enzymeSequenceInitialCourtPosition" readonly="readonly"/>
			</div>
			<div class="span4">
				<label for="plasmidId">
					<s:message code="enzyme.final" />
				</label>
				<input type="text" id="enzymeFinalName" name="enzymeFinalName" readonly="readonly"/>
				<input type="text" id="enzymeFinalAccession" name="enzymeFinalAccession" readonly="readonly"/>
				<input type="hidden" id="enzymeFinalId" name="enzymeFinalId" readonly="readonly"/>
				
				<input type="hidden" id="enzymePlasmidFinalCourtPositionList" name="enzymePlasmidFinalCourtPositionList" readonly="readonly"/>
				
				<label for="enzymeSequenceFinalCourtPosition">
					<s:message code="enzyme.sequence.court.final" />
				</label>
				<input type="text" id="enzymeSequenceFinalCourtPosition" name="enzymeSequenceFinalCourtPosition" readonly="readonly"/>
			</div>
			
			<input type="hidden" id="inputName" name="inputName" class="input-block-level" value="${inputedName}" />
			<input type="hidden" id="inputSequence" name="inputSequence" value="${inputedSequence}" />
		</div>
		
		<div class="form-actions">
			<button type="submit" class="btn btn-primary">
				<s:message code="common.ok" /> 
			</button>

			<a href='<s:url value="/"></s:url>' class="btn">
				<s:message code="common.cancel" />
			</a>
		</div>

		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr>
					<th>
						#
					</th>
					<th>
						<s:message code="common.name" />
					</th>
					<th>
						<s:message code="common.accession" />
					</th>
					<th>
						<s:message code="enzyme.codon.principal.value" />
					</th>
					<th>
						<s:message code="enzyme.codon.principal.position" />
					</th>
					<th>
						<s:message code="enzyme.codon.compl.value" />
					</th>
					<th>
						<s:message code="enzyme.codon.compl.position" />
					</th>
					<th>
						<s:message code="enzyme.initial.label" />
					</th>
					<th>
						<s:message code="enzyme.final.label" />
					</th>
				</tr>
			</thead>
			
			<tbody>
				<c:forEach items="${enzymeList}" var="enzyme">
					<input type="hidden" id="enzymeId-${enzyme.id}" value="${enzyme.id}"/>
					
					<tr>
						<td>
							${enzyme.id}
						</td>
						<td>
							${enzyme.name}
						</td>
						<td>
							${enzyme.accession}
						</td>
						<td>
							${enzyme.principalValue}
						</td>
						<td>
							${enzyme.principalCourtPosition}
						</td>
						<td>
							${enzyme.complementValue}
						</td>
						<td>
							${enzyme.complementCourtPosition}
						</td>
						<td>
							<a href='#' class="btn" onclick="chooseInitialEnzyme(${enzyme.id}, ${enzyme.firstSequenceCourtPosition}, ${enzyme.plasmidCourtPosition}, '${enzyme.accession}', '${enzyme.name}');">
								<i class="icon-check" > </i>
							</a>
						</td>
						<td>
							<a href='#' class="btn" onclick="chooseFinalEnzyme(${enzyme.id}, ${enzyme.lastSequenceCourtPosition}, ${enzyme.plasmidCourtPosition}, '${enzyme.accession}', '${enzyme.name}');">
								<i class="icon-check" > </i>
							</a>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>

	</form>
</fieldset>

<script type="text/javascript">
	function chooseInitialEnzyme(id, courtPosition, plasmidCourtPosition, accession, name) {
		$('#enzymeInitialId').val(id);
		$('#enzymeSequenceInitialCourtPosition').val(courtPosition);
		$('#enzymePlasmidInitialCourtPositionList').val(plasmidCourtPosition);
		$('#enzymeInitialAccession').val(accession);
		$('#enzymeInitialName').val(accession);
	}
	
	function chooseFinalEnzyme(id, courtPosition, plasmidCourtPosition, accession, name) {
		$('#enzymeFinalId').val(id);
		$('#enzymeSequenceFinalCourtPosition').val(courtPosition);
		$('#enzymePlasmidFinalCourtPositionList').val(plasmidCourtPosition);
		$('#enzymeFinalAccession').val(accession);
		$('#enzymeFinalName').val(accession);
	}
</script>